export const INCREMENT_WORK_TIME = 'INCREMENT_WORK_TIME';
export const DECREMENT_WORK_TIME = 'DECREMENT_WORK_TIME';
export const INCREMENT_BREAK_TIME = 'INCREMENT_BREAK_TIME';
export const DECREMENT_BREAK_TIME = 'DECREMENT_BREAK_TIME';
